apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.metadata.name }}
  namespace: {{ .Values.service.metadata.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deployment.template.metadata.labels.app }}
  ports:
  - port: 80
    protocol: TCP
